GET http://localhost:5000/emp-api/employee

###
POST http://localhost:5000/emp-api/employee
Content-Type: application/json

{
    "name":"amulya",
    "email":"amulya@gmail.com",
    "mobile":1234567890,
    "designation":"DA",
    "companyname":"Microsoft"
}
###
PUT  http://localhost:5000/emp-api/employee/69ca2cd7de99cc3bf28848cb
Content-Type: application/json

{
    "name":"amulya",
    "email":"amulya@gmail.com",
    "mobile":1234567890,
    "designation":"DA",
    "companyname":"Google"
}

###
DELETE http://localhost:5000/emp-api/employee/69ca2cd7de99cc3bf28848cb