//server sends the request
GET  http://localhost:3000/user-api/users

###
//Read a user by id 
GET http://localhost:3000/user-api/users/2

###
//the client sends the request 
POST  http://localhost:3000/user-api/users 
Content-Type: application/json

{
    "id":2,
    "name":"ram",
    "age":20
}

###
//update the resorce
PUT  http://localhost:3000/user-api/users
Content-Type: application/json

{
   "id":2,
    "name":"ram",
    "age":22 
}
###
DELETE http://localhost:3000/user-api/users/2

//post request and push request should send data to the api as body of the request object
//get and delete request do not support body of the request object. 
//So that these two requests can send data through end point
###
GET  http://localhost:3000/product-api/products

###
POST  http://localhost:3000/product-api/products
Content-Type: application/json

{
    "id":1,
    "name":"ram",
    "age":20
}
###

PUT   http://localhost:3000/product-api/products 
Content-Type: application/json

{
   "id":1,
    "name":"raju",
    "age":22
}
###
DELETE  http://localhost:3000/product-api/products/1